'use strict';

const STREAM_STATE = Object.freeze({
  DRAFT: 'DRAFT',
  QUEUED: 'QUEUED',
  ALLOCATING: 'ALLOCATING',
  PREPARING: 'PREPARING',
  STARTING: 'STARTING',
  CONNECTING: 'CONNECTING',
  LIVE: 'LIVE',
  DEGRADED: 'DEGRADED',
  RECOVERING: 'RECOVERING',
  STOPPING: 'STOPPING',
  STOPPED: 'STOPPED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
});

const TERMINAL_STATES = new Set([STREAM_STATE.STOPPED, STREAM_STATE.FAILED, STREAM_STATE.CANCELLED]);

const TRANSITIONS = Object.freeze({
  DRAFT: new Set(['QUEUED', 'CANCELLED']),
  QUEUED: new Set(['ALLOCATING', 'CANCELLED', 'FAILED']),
  ALLOCATING: new Set(['PREPARING', 'QUEUED', 'STOPPING', 'FAILED']),
  PREPARING: new Set(['STARTING', 'RECOVERING', 'STOPPING', 'FAILED']),
  STARTING: new Set(['CONNECTING', 'RECOVERING', 'STOPPING', 'FAILED']),
  CONNECTING: new Set(['LIVE', 'DEGRADED', 'RECOVERING', 'STOPPING', 'FAILED']),
  LIVE: new Set(['DEGRADED', 'RECOVERING', 'STOPPING', 'FAILED']),
  DEGRADED: new Set(['LIVE', 'RECOVERING', 'STOPPING', 'FAILED']),
  RECOVERING: new Set(['ALLOCATING', 'PREPARING', 'STARTING', 'CONNECTING', 'LIVE', 'STOPPING', 'FAILED']),
  STOPPING: new Set(['STOPPED', 'FAILED']),
  STOPPED: new Set(),
  FAILED: new Set(),
  CANCELLED: new Set()
});

module.exports = { STREAM_STATE, TERMINAL_STATES, TRANSITIONS };
